name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [main]  # cambia si tu rama principal es otra
  workflow_dispatch:   # permite lanzarlo manualmente

permissions:
  contents: read
  pages: write
  id-token: write      # requerido por `deploy-pages`

concurrency:           # evita despliegues simult치neos
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20   # o la versi칩n que uses

      - name: Install deps
        run: npm ci          # m치s seguro que `npm i`

      - name: Build
        run: npm run build   # deja el artefacto en ./dist

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist       # carpeta a publicar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # acci칩n oficial :contentReference[oaicite:1]{index=1}
